
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Threading.Tasks;
using Babu.Config;
using GameConfig.Config;

namespace GameConfig
{
    public class Configs
    {
        public static int LeftCount = 121;

        public static AchievementConfigTable Achievement { get; set; }
        public static ActivityConfigTable Activity { get; set; }
        public static ActivityBattlePassRewardConfigTable ActivityBattlePassReward { get; set; }
        public static ActivityPayDailyRewardConfigTable ActivityPayDailyReward { get; set; }
        public static ActivityPayRewardConfigTable ActivityPayReward { get; set; }
        public static ActivityTopRewardConfigTable ActivityTopReward { get; set; }
        public static AllRankRewardConfigTable AllRankReward { get; set; }
        public static AllStarAdditionConfigTable AllStarAddition { get; set; }
        public static AllStarGroupConfigTable AllStarGroup { get; set; }
        public static AllStarRewardConfigTable AllStarReward { get; set; }
        public static AllfontConfigTable Allfont { get; set; }
        public static ArenaBattleResultConfigTable ArenaBattleResult { get; set; }
        public static ArenaClubConfigTable ArenaClub { get; set; }
        public static ArenaPlayerConfigTable ArenaPlayer { get; set; }
        public static ArenaRewardConfigTable ArenaReward { get; set; }
        public static ArenaShopConfigTable ArenaShop { get; set; }
        public static ArenaStageConfigTable ArenaStage { get; set; }
        public static BountyTaskConfigTable BountyTask { get; set; }
        public static BountyTaskBoxConfigTable BountyTaskBox { get; set; }
        public static BoxConfigTable Box { get; set; }
        public static BreakConfigTable Break { get; set; }
        public static BuffTypeConfigTable BuffType { get; set; }
        public static CardAbilityConfigTable CardAbility { get; set; }
        public static CardBuffTypeConfigTable CardBuffType { get; set; }
        public static CardFireConfigTable CardFire { get; set; }
        public static CardLevelConfigTable CardLevel { get; set; }
        public static CardModelConfigTable CardModel { get; set; }
        public static CardPoolConfigTable CardPool { get; set; }
        public static CardPoolGroupConfigTable CardPoolGroup { get; set; }
        public static CardPoolInfoConfigTable CardPoolInfo { get; set; }
        public static CardUpgradeConfigTable CardUpgrade { get; set; }
        public static ChallengeClubConfigTable ChallengeClub { get; set; }
        public static ChallengeCountryConfigTable ChallengeCountry { get; set; }
        public static ChallengeHeroConfigTable ChallengeHero { get; set; }
        public static ChallengeHeroChapterConfigTable ChallengeHeroChapter { get; set; }
        public static ChallengeMapConfigTable ChallengeMap { get; set; }
        public static ChallengePlayerConfigTable ChallengePlayer { get; set; }
        public static ChallengeRuleConfigTable ChallengeRule { get; set; }
        public static ClubConfigTable Club { get; set; }
        public static CommonTriggerConfigTable CommonTrigger { get; set; }
        public static CupCourseConfigTable CupCourse { get; set; }
        public static CupRewardOtherConfigTable CupRewardOther { get; set; }
        public static CupRewardRankConfigTable CupRewardRank { get; set; }
        public static DiamondShopConfigTable DiamondShop { get; set; }
        public static DragonBoatRewardConfigTable DragonBoatReward { get; set; }
        public static EnergyTimeLimitConfigTable EnergyTimeLimit { get; set; }
        public static ExampleConfigTable Example { get; set; }
        public static FestivalBoxConfigTable FestivalBox { get; set; }
        public static FestivalLoginConfigTable FestivalLogin { get; set; }
        public static FestivalTaskConfigTable FestivalTask { get; set; }
        public static FestivalTravelConfigTable FestivalTravel { get; set; }
        public static FightStatConfigTable FightStat { get; set; }
        public static FinalsGuessCourseConfigTable FinalsGuessCourse { get; set; }
        public static FinalsGuessPlayerConfigTable FinalsGuessPlayer { get; set; }
        public static FinalsGuessRewardConfigTable FinalsGuessReward { get; set; }
        public static FinalsGuessTeamConfigTable FinalsGuessTeam { get; set; }
        public static FirstChargeRewardConfigTable FirstChargeReward { get; set; }
        public static FormationBoardConfigTable FormationBoard { get; set; }
        public static GameBroadcastConfigTable GameBroadcast { get; set; }
        public static GameItemShopConfigTable GameItemShop { get; set; }
        public static GiftShopConfigTable GiftShop { get; set; }
        public static GiftSkillConfigTable GiftSkill { get; set; }
        public static GoodsConfigTable Goods { get; set; }
        public static GuideConfigTable Guide { get; set; }
        public static GuideDialogueConfigTable GuideDialogue { get; set; }
        public static GuideEmailConfigTable GuideEmail { get; set; }
        public static HundredChampionCourseConfigTable HundredChampionCourse { get; set; }
        public static HundredPlayoffCourseConfigTable HundredPlayoffCourse { get; set; }
        public static HundredRewardConfigTable HundredReward { get; set; }
        public static JerseyBreakConfigTable JerseyBreak { get; set; }
        public static JerseyUpgradeConfigTable JerseyUpgrade { get; set; }
        public static KeyframeActionConfigTable KeyframeAction { get; set; }
        public static LangConfigTable Lang { get; set; }
        public static LeagueCourseConfigTable LeagueCourse { get; set; }
        public static LeagueRewardOtherConfigTable LeagueRewardOther { get; set; }
        public static LeagueRewardRankConfigTable LeagueRewardRank { get; set; }
        public static MainTaskTitleConfigTable MainTaskTitle { get; set; }
        public static ModuleDefineConfigTable ModuleDefine { get; set; }
        public static MonthCardShopConfigTable MonthCardShop { get; set; }
        public static MoonSiginAddedRewardConfigTable MoonSiginAddedReward { get; set; }
        public static MoonSiginRewardConfigTable MoonSiginReward { get; set; }
        public static NftCardIconConfigTable NftCardIcon { get; set; }
        public static NftGoodsConfigTable NftGoods { get; set; }
        public static NoviceTargetTaskConfigTable NoviceTargetTask { get; set; }
        public static NpcCardConfigTable NpcCard { get; set; }
        public static OptionRewardsConfigTable OptionRewards { get; set; }
        public static OptionsConfigTable Options { get; set; }
        public static PositionConfigTable Position { get; set; }
        public static ProductPriceConfigTable ProductPrice { get; set; }
        public static QualityStarConfigTable QualityStar { get; set; }
        public static QualityUpgradeConfigTable QualityUpgrade { get; set; }
        public static RandomClubIconConfigTable RandomClubIcon { get; set; }
        public static RandomClubNameConfigTable RandomClubName { get; set; }
        public static RandomRobotNameConfigTable RandomRobotName { get; set; }
        public static SeparatedPositionConfigTable SeparatedPosition { get; set; }
        public static SevenDayLoginRewardConfigTable SevenDayLoginReward { get; set; }
        public static ShootGameAddedRewardConfigTable ShootGameAddedReward { get; set; }
        public static ShootGameStageConfigTable ShootGameStage { get; set; }
        public static SkillConfigTable Skill { get; set; }
        public static SkillAdditionConfigTable SkillAddition { get; set; }
        public static SkillUpgradeConfigTable SkillUpgrade { get; set; }
        public static StrengthenConfigTable Strengthen { get; set; }
        public static SysFormationConfigTable SysFormation { get; set; }
        public static SysTacticsConfigTable SysTactics { get; set; }
        public static TacticsConfigTable Tactics { get; set; }
        public static TacticsTypeConfigTable TacticsType { get; set; }
        public static TacticsUpgradeConfigTable TacticsUpgrade { get; set; }
        public static TaskConfigTable Task { get; set; }
        public static TaskDemandConfigTable TaskDemand { get; set; }
        public static TaskRewardBoxConfigTable TaskRewardBox { get; set; }
        public static TowerConfigTable Tower { get; set; }
        public static TowerChapterConfigTable TowerChapter { get; set; }
        public static TowerStarRewardConfigTable TowerStarReward { get; set; }
        public static TrainConfigTable Train { get; set; }
        public static TrainShopConfigTable TrainShop { get; set; }
        public static TriggerConfigTable Trigger { get; set; }
        public static UnitConfigTable Unit { get; set; }
        public static UserLevelConfigTable UserLevel { get; set; }
        public static WayOfDescConfigTable WayOfDesc { get; set; }
        public static WayOfGainConfigTable WayOfGain { get; set; }
        public static WishSignConfigTable WishSign { get; set; }

        public static void LoadAll()
        {
            Achievement = ConfigManager.Instance.LoadTable<AchievementConfigTable>("cfg_achievement");
            Activity = ConfigManager.Instance.LoadTable<ActivityConfigTable>("cfg_activity");
            ActivityBattlePassReward = ConfigManager.Instance.LoadTable<ActivityBattlePassRewardConfigTable>("cfg_activity_battle_pass_reward");
            ActivityPayDailyReward = ConfigManager.Instance.LoadTable<ActivityPayDailyRewardConfigTable>("cfg_activity_pay_daily_reward");
            ActivityPayReward = ConfigManager.Instance.LoadTable<ActivityPayRewardConfigTable>("cfg_activity_pay_reward");
            ActivityTopReward = ConfigManager.Instance.LoadTable<ActivityTopRewardConfigTable>("cfg_activity_top_reward");
            AllRankReward = ConfigManager.Instance.LoadTable<AllRankRewardConfigTable>("cfg_all_rank_reward");
            AllStarAddition = ConfigManager.Instance.LoadTable<AllStarAdditionConfigTable>("cfg_all_star_addition");
            AllStarGroup = ConfigManager.Instance.LoadTable<AllStarGroupConfigTable>("cfg_all_star_group");
            AllStarReward = ConfigManager.Instance.LoadTable<AllStarRewardConfigTable>("cfg_all_star_reward");
            Allfont = ConfigManager.Instance.LoadTable<AllfontConfigTable>("cfg_allfont");
            ArenaBattleResult = ConfigManager.Instance.LoadTable<ArenaBattleResultConfigTable>("cfg_arena_battle_result");
            ArenaClub = ConfigManager.Instance.LoadTable<ArenaClubConfigTable>("cfg_arena_club");
            ArenaPlayer = ConfigManager.Instance.LoadTable<ArenaPlayerConfigTable>("cfg_arena_player");
            ArenaReward = ConfigManager.Instance.LoadTable<ArenaRewardConfigTable>("cfg_arena_reward");
            ArenaShop = ConfigManager.Instance.LoadTable<ArenaShopConfigTable>("cfg_arena_shop");
            ArenaStage = ConfigManager.Instance.LoadTable<ArenaStageConfigTable>("cfg_arena_stage");
            BountyTask = ConfigManager.Instance.LoadTable<BountyTaskConfigTable>("cfg_bounty_task");
            BountyTaskBox = ConfigManager.Instance.LoadTable<BountyTaskBoxConfigTable>("cfg_bounty_task_box");
            Box = ConfigManager.Instance.LoadTable<BoxConfigTable>("cfg_box");
            Break = ConfigManager.Instance.LoadTable<BreakConfigTable>("cfg_break");
            BuffType = ConfigManager.Instance.LoadTable<BuffTypeConfigTable>("cfg_buff_type");
            CardAbility = ConfigManager.Instance.LoadTable<CardAbilityConfigTable>("cfg_card_ability");
            CardBuffType = ConfigManager.Instance.LoadTable<CardBuffTypeConfigTable>("cfg_card_buff_type");
            CardFire = ConfigManager.Instance.LoadTable<CardFireConfigTable>("cfg_card_fire");
            CardLevel = ConfigManager.Instance.LoadTable<CardLevelConfigTable>("cfg_card_level");
            CardModel = ConfigManager.Instance.LoadTable<CardModelConfigTable>("cfg_card_model");
            CardPool = ConfigManager.Instance.LoadTable<CardPoolConfigTable>("cfg_card_pool");
            CardPoolGroup = ConfigManager.Instance.LoadTable<CardPoolGroupConfigTable>("cfg_card_pool_group");
            CardPoolInfo = ConfigManager.Instance.LoadTable<CardPoolInfoConfigTable>("cfg_card_pool_info");
            CardUpgrade = ConfigManager.Instance.LoadTable<CardUpgradeConfigTable>("cfg_card_upgrade");
            ChallengeClub = ConfigManager.Instance.LoadTable<ChallengeClubConfigTable>("cfg_challenge_club");
            ChallengeCountry = ConfigManager.Instance.LoadTable<ChallengeCountryConfigTable>("cfg_challenge_country");
            ChallengeHero = ConfigManager.Instance.LoadTable<ChallengeHeroConfigTable>("cfg_challenge_hero");
            ChallengeHeroChapter = ConfigManager.Instance.LoadTable<ChallengeHeroChapterConfigTable>("cfg_challenge_hero_chapter");
            ChallengeMap = ConfigManager.Instance.LoadTable<ChallengeMapConfigTable>("cfg_challenge_map");
            ChallengePlayer = ConfigManager.Instance.LoadTable<ChallengePlayerConfigTable>("cfg_challenge_player");
            ChallengeRule = ConfigManager.Instance.LoadTable<ChallengeRuleConfigTable>("cfg_challenge_rule");
            Club = ConfigManager.Instance.LoadTable<ClubConfigTable>("cfg_club");
            CommonTrigger = ConfigManager.Instance.LoadTable<CommonTriggerConfigTable>("cfg_common_trigger");
            CupCourse = ConfigManager.Instance.LoadTable<CupCourseConfigTable>("cfg_cup_course");
            CupRewardOther = ConfigManager.Instance.LoadTable<CupRewardOtherConfigTable>("cfg_cup_reward_other");
            CupRewardRank = ConfigManager.Instance.LoadTable<CupRewardRankConfigTable>("cfg_cup_reward_rank");
            DiamondShop = ConfigManager.Instance.LoadTable<DiamondShopConfigTable>("cfg_diamond_shop");
            DragonBoatReward = ConfigManager.Instance.LoadTable<DragonBoatRewardConfigTable>("cfg_dragon_boat_reward");
            EnergyTimeLimit = ConfigManager.Instance.LoadTable<EnergyTimeLimitConfigTable>("cfg_energy_time_limit");
            Example = ConfigManager.Instance.LoadTable<ExampleConfigTable>("cfg_example");
            FestivalBox = ConfigManager.Instance.LoadTable<FestivalBoxConfigTable>("cfg_festival_box");
            FestivalLogin = ConfigManager.Instance.LoadTable<FestivalLoginConfigTable>("cfg_festival_login");
            FestivalTask = ConfigManager.Instance.LoadTable<FestivalTaskConfigTable>("cfg_festival_task");
            FestivalTravel = ConfigManager.Instance.LoadTable<FestivalTravelConfigTable>("cfg_festival_travel");
            FightStat = ConfigManager.Instance.LoadTable<FightStatConfigTable>("cfg_fight_stat");
            FinalsGuessCourse = ConfigManager.Instance.LoadTable<FinalsGuessCourseConfigTable>("cfg_finals_guess_course");
            FinalsGuessPlayer = ConfigManager.Instance.LoadTable<FinalsGuessPlayerConfigTable>("cfg_finals_guess_player");
            FinalsGuessReward = ConfigManager.Instance.LoadTable<FinalsGuessRewardConfigTable>("cfg_finals_guess_reward");
            FinalsGuessTeam = ConfigManager.Instance.LoadTable<FinalsGuessTeamConfigTable>("cfg_finals_guess_team");
            FirstChargeReward = ConfigManager.Instance.LoadTable<FirstChargeRewardConfigTable>("cfg_first_charge_reward");
            FormationBoard = ConfigManager.Instance.LoadTable<FormationBoardConfigTable>("cfg_formation_board");
            GameBroadcast = ConfigManager.Instance.LoadTable<GameBroadcastConfigTable>("cfg_game_broadcast");
            GameItemShop = ConfigManager.Instance.LoadTable<GameItemShopConfigTable>("cfg_game_item_shop");
            GiftShop = ConfigManager.Instance.LoadTable<GiftShopConfigTable>("cfg_gift_shop");
            GiftSkill = ConfigManager.Instance.LoadTable<GiftSkillConfigTable>("cfg_gift_skill");
            Goods = ConfigManager.Instance.LoadTable<GoodsConfigTable>("cfg_goods");
            Guide = ConfigManager.Instance.LoadTable<GuideConfigTable>("cfg_guide");
            GuideDialogue = ConfigManager.Instance.LoadTable<GuideDialogueConfigTable>("cfg_guide_dialogue");
            GuideEmail = ConfigManager.Instance.LoadTable<GuideEmailConfigTable>("cfg_guide_email");
            HundredChampionCourse = ConfigManager.Instance.LoadTable<HundredChampionCourseConfigTable>("cfg_hundred_champion_course");
            HundredPlayoffCourse = ConfigManager.Instance.LoadTable<HundredPlayoffCourseConfigTable>("cfg_hundred_playoff_course");
            HundredReward = ConfigManager.Instance.LoadTable<HundredRewardConfigTable>("cfg_hundred_reward");
            JerseyBreak = ConfigManager.Instance.LoadTable<JerseyBreakConfigTable>("cfg_jersey_break");
            JerseyUpgrade = ConfigManager.Instance.LoadTable<JerseyUpgradeConfigTable>("cfg_jersey_upgrade");
            KeyframeAction = ConfigManager.Instance.LoadTable<KeyframeActionConfigTable>("cfg_keyframe_action");
            Lang = ConfigManager.Instance.LoadTable<LangConfigTable>("cfg_lang");
            LeagueCourse = ConfigManager.Instance.LoadTable<LeagueCourseConfigTable>("cfg_league_course");
            LeagueRewardOther = ConfigManager.Instance.LoadTable<LeagueRewardOtherConfigTable>("cfg_league_reward_other");
            LeagueRewardRank = ConfigManager.Instance.LoadTable<LeagueRewardRankConfigTable>("cfg_league_reward_rank");
            MainTaskTitle = ConfigManager.Instance.LoadTable<MainTaskTitleConfigTable>("cfg_main_task_title");
            ModuleDefine = ConfigManager.Instance.LoadTable<ModuleDefineConfigTable>("cfg_module_define");
            MonthCardShop = ConfigManager.Instance.LoadTable<MonthCardShopConfigTable>("cfg_month_card_shop");
            MoonSiginAddedReward = ConfigManager.Instance.LoadTable<MoonSiginAddedRewardConfigTable>("cfg_moon_sigin_added_reward");
            MoonSiginReward = ConfigManager.Instance.LoadTable<MoonSiginRewardConfigTable>("cfg_moon_sigin_reward");
            NftCardIcon = ConfigManager.Instance.LoadTable<NftCardIconConfigTable>("cfg_nft_card_icon");
            NftGoods = ConfigManager.Instance.LoadTable<NftGoodsConfigTable>("cfg_nft_goods");
            NoviceTargetTask = ConfigManager.Instance.LoadTable<NoviceTargetTaskConfigTable>("cfg_novice_target_task");
            NpcCard = ConfigManager.Instance.LoadTable<NpcCardConfigTable>("cfg_npc_card");
            OptionRewards = ConfigManager.Instance.LoadTable<OptionRewardsConfigTable>("cfg_option_rewards");
            Options = ConfigManager.Instance.LoadTable<OptionsConfigTable>("cfg_options");
            Position = ConfigManager.Instance.LoadTable<PositionConfigTable>("cfg_position");
            ProductPrice = ConfigManager.Instance.LoadTable<ProductPriceConfigTable>("cfg_product_price");
            QualityStar = ConfigManager.Instance.LoadTable<QualityStarConfigTable>("cfg_quality_star");
            QualityUpgrade = ConfigManager.Instance.LoadTable<QualityUpgradeConfigTable>("cfg_quality_upgrade");
            RandomClubIcon = ConfigManager.Instance.LoadTable<RandomClubIconConfigTable>("cfg_random_club_icon");
            RandomClubName = ConfigManager.Instance.LoadTable<RandomClubNameConfigTable>("cfg_random_club_name");
            RandomRobotName = ConfigManager.Instance.LoadTable<RandomRobotNameConfigTable>("cfg_random_robot_name");
            SeparatedPosition = ConfigManager.Instance.LoadTable<SeparatedPositionConfigTable>("cfg_separated_position");
            SevenDayLoginReward = ConfigManager.Instance.LoadTable<SevenDayLoginRewardConfigTable>("cfg_seven_day_login_reward");
            ShootGameAddedReward = ConfigManager.Instance.LoadTable<ShootGameAddedRewardConfigTable>("cfg_shoot_game_added_reward");
            ShootGameStage = ConfigManager.Instance.LoadTable<ShootGameStageConfigTable>("cfg_shoot_game_stage");
            Skill = ConfigManager.Instance.LoadTable<SkillConfigTable>("cfg_skill");
            SkillAddition = ConfigManager.Instance.LoadTable<SkillAdditionConfigTable>("cfg_skill_addition");
            SkillUpgrade = ConfigManager.Instance.LoadTable<SkillUpgradeConfigTable>("cfg_skill_upgrade");
            Strengthen = ConfigManager.Instance.LoadTable<StrengthenConfigTable>("cfg_strengthen");
            SysFormation = ConfigManager.Instance.LoadTable<SysFormationConfigTable>("cfg_sys_formation");
            SysTactics = ConfigManager.Instance.LoadTable<SysTacticsConfigTable>("cfg_sys_tactics");
            Tactics = ConfigManager.Instance.LoadTable<TacticsConfigTable>("cfg_tactics");
            TacticsType = ConfigManager.Instance.LoadTable<TacticsTypeConfigTable>("cfg_tactics_type");
            TacticsUpgrade = ConfigManager.Instance.LoadTable<TacticsUpgradeConfigTable>("cfg_tactics_upgrade");
            Task = ConfigManager.Instance.LoadTable<TaskConfigTable>("cfg_task");
            TaskDemand = ConfigManager.Instance.LoadTable<TaskDemandConfigTable>("cfg_task_demand");
            TaskRewardBox = ConfigManager.Instance.LoadTable<TaskRewardBoxConfigTable>("cfg_task_reward_box");
            Tower = ConfigManager.Instance.LoadTable<TowerConfigTable>("cfg_tower");
            TowerChapter = ConfigManager.Instance.LoadTable<TowerChapterConfigTable>("cfg_tower_chapter");
            TowerStarReward = ConfigManager.Instance.LoadTable<TowerStarRewardConfigTable>("cfg_tower_star_reward");
            Train = ConfigManager.Instance.LoadTable<TrainConfigTable>("cfg_train");
            TrainShop = ConfigManager.Instance.LoadTable<TrainShopConfigTable>("cfg_train_shop");
            Trigger = ConfigManager.Instance.LoadTable<TriggerConfigTable>("cfg_trigger");
            Unit = ConfigManager.Instance.LoadTable<UnitConfigTable>("cfg_unit");
            UserLevel = ConfigManager.Instance.LoadTable<UserLevelConfigTable>("cfg_user_level");
            WayOfDesc = ConfigManager.Instance.LoadTable<WayOfDescConfigTable>("cfg_way_of_desc");
            WayOfGain = ConfigManager.Instance.LoadTable<WayOfGainConfigTable>("cfg_way_of_gain");
            WishSign = ConfigManager.Instance.LoadTable<WishSignConfigTable>("cfg_wish_sign");
        }

        public static Task LoadAllAsync()
        {
            ConfigManager.Instance.LoadTableAsync<AchievementConfigTable>("cfg_achievement", v => { Achievement = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ActivityConfigTable>("cfg_activity", v => { Activity = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ActivityBattlePassRewardConfigTable>("cfg_activity_battle_pass_reward", v => { ActivityBattlePassReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ActivityPayDailyRewardConfigTable>("cfg_activity_pay_daily_reward", v => { ActivityPayDailyReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ActivityPayRewardConfigTable>("cfg_activity_pay_reward", v => { ActivityPayReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ActivityTopRewardConfigTable>("cfg_activity_top_reward", v => { ActivityTopReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<AllRankRewardConfigTable>("cfg_all_rank_reward", v => { AllRankReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<AllStarAdditionConfigTable>("cfg_all_star_addition", v => { AllStarAddition = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<AllStarGroupConfigTable>("cfg_all_star_group", v => { AllStarGroup = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<AllStarRewardConfigTable>("cfg_all_star_reward", v => { AllStarReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<AllfontConfigTable>("cfg_allfont", v => { Allfont = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaBattleResultConfigTable>("cfg_arena_battle_result", v => { ArenaBattleResult = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaClubConfigTable>("cfg_arena_club", v => { ArenaClub = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaPlayerConfigTable>("cfg_arena_player", v => { ArenaPlayer = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaRewardConfigTable>("cfg_arena_reward", v => { ArenaReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaShopConfigTable>("cfg_arena_shop", v => { ArenaShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ArenaStageConfigTable>("cfg_arena_stage", v => { ArenaStage = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<BountyTaskConfigTable>("cfg_bounty_task", v => { BountyTask = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<BountyTaskBoxConfigTable>("cfg_bounty_task_box", v => { BountyTaskBox = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<BoxConfigTable>("cfg_box", v => { Box = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<BreakConfigTable>("cfg_break", v => { Break = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<BuffTypeConfigTable>("cfg_buff_type", v => { BuffType = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardAbilityConfigTable>("cfg_card_ability", v => { CardAbility = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardBuffTypeConfigTable>("cfg_card_buff_type", v => { CardBuffType = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardFireConfigTable>("cfg_card_fire", v => { CardFire = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardLevelConfigTable>("cfg_card_level", v => { CardLevel = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardModelConfigTable>("cfg_card_model", v => { CardModel = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardPoolConfigTable>("cfg_card_pool", v => { CardPool = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardPoolGroupConfigTable>("cfg_card_pool_group", v => { CardPoolGroup = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardPoolInfoConfigTable>("cfg_card_pool_info", v => { CardPoolInfo = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CardUpgradeConfigTable>("cfg_card_upgrade", v => { CardUpgrade = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeClubConfigTable>("cfg_challenge_club", v => { ChallengeClub = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeCountryConfigTable>("cfg_challenge_country", v => { ChallengeCountry = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeHeroConfigTable>("cfg_challenge_hero", v => { ChallengeHero = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeHeroChapterConfigTable>("cfg_challenge_hero_chapter", v => { ChallengeHeroChapter = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeMapConfigTable>("cfg_challenge_map", v => { ChallengeMap = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengePlayerConfigTable>("cfg_challenge_player", v => { ChallengePlayer = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ChallengeRuleConfigTable>("cfg_challenge_rule", v => { ChallengeRule = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ClubConfigTable>("cfg_club", v => { Club = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CommonTriggerConfigTable>("cfg_common_trigger", v => { CommonTrigger = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CupCourseConfigTable>("cfg_cup_course", v => { CupCourse = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CupRewardOtherConfigTable>("cfg_cup_reward_other", v => { CupRewardOther = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<CupRewardRankConfigTable>("cfg_cup_reward_rank", v => { CupRewardRank = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<DiamondShopConfigTable>("cfg_diamond_shop", v => { DiamondShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<DragonBoatRewardConfigTable>("cfg_dragon_boat_reward", v => { DragonBoatReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<EnergyTimeLimitConfigTable>("cfg_energy_time_limit", v => { EnergyTimeLimit = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ExampleConfigTable>("cfg_example", v => { Example = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FestivalBoxConfigTable>("cfg_festival_box", v => { FestivalBox = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FestivalLoginConfigTable>("cfg_festival_login", v => { FestivalLogin = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FestivalTaskConfigTable>("cfg_festival_task", v => { FestivalTask = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FestivalTravelConfigTable>("cfg_festival_travel", v => { FestivalTravel = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FightStatConfigTable>("cfg_fight_stat", v => { FightStat = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FinalsGuessCourseConfigTable>("cfg_finals_guess_course", v => { FinalsGuessCourse = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FinalsGuessPlayerConfigTable>("cfg_finals_guess_player", v => { FinalsGuessPlayer = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FinalsGuessRewardConfigTable>("cfg_finals_guess_reward", v => { FinalsGuessReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FinalsGuessTeamConfigTable>("cfg_finals_guess_team", v => { FinalsGuessTeam = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FirstChargeRewardConfigTable>("cfg_first_charge_reward", v => { FirstChargeReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<FormationBoardConfigTable>("cfg_formation_board", v => { FormationBoard = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GameBroadcastConfigTable>("cfg_game_broadcast", v => { GameBroadcast = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GameItemShopConfigTable>("cfg_game_item_shop", v => { GameItemShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GiftShopConfigTable>("cfg_gift_shop", v => { GiftShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GiftSkillConfigTable>("cfg_gift_skill", v => { GiftSkill = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GoodsConfigTable>("cfg_goods", v => { Goods = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GuideConfigTable>("cfg_guide", v => { Guide = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GuideDialogueConfigTable>("cfg_guide_dialogue", v => { GuideDialogue = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<GuideEmailConfigTable>("cfg_guide_email", v => { GuideEmail = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<HundredChampionCourseConfigTable>("cfg_hundred_champion_course", v => { HundredChampionCourse = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<HundredPlayoffCourseConfigTable>("cfg_hundred_playoff_course", v => { HundredPlayoffCourse = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<HundredRewardConfigTable>("cfg_hundred_reward", v => { HundredReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<JerseyBreakConfigTable>("cfg_jersey_break", v => { JerseyBreak = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<JerseyUpgradeConfigTable>("cfg_jersey_upgrade", v => { JerseyUpgrade = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<KeyframeActionConfigTable>("cfg_keyframe_action", v => { KeyframeAction = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<LangConfigTable>("cfg_lang", v => { Lang = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<LeagueCourseConfigTable>("cfg_league_course", v => { LeagueCourse = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<LeagueRewardOtherConfigTable>("cfg_league_reward_other", v => { LeagueRewardOther = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<LeagueRewardRankConfigTable>("cfg_league_reward_rank", v => { LeagueRewardRank = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<MainTaskTitleConfigTable>("cfg_main_task_title", v => { MainTaskTitle = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ModuleDefineConfigTable>("cfg_module_define", v => { ModuleDefine = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<MonthCardShopConfigTable>("cfg_month_card_shop", v => { MonthCardShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<MoonSiginAddedRewardConfigTable>("cfg_moon_sigin_added_reward", v => { MoonSiginAddedReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<MoonSiginRewardConfigTable>("cfg_moon_sigin_reward", v => { MoonSiginReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<NftCardIconConfigTable>("cfg_nft_card_icon", v => { NftCardIcon = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<NftGoodsConfigTable>("cfg_nft_goods", v => { NftGoods = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<NoviceTargetTaskConfigTable>("cfg_novice_target_task", v => { NoviceTargetTask = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<NpcCardConfigTable>("cfg_npc_card", v => { NpcCard = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<OptionRewardsConfigTable>("cfg_option_rewards", v => { OptionRewards = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<OptionsConfigTable>("cfg_options", v => { Options = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<PositionConfigTable>("cfg_position", v => { Position = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ProductPriceConfigTable>("cfg_product_price", v => { ProductPrice = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<QualityStarConfigTable>("cfg_quality_star", v => { QualityStar = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<QualityUpgradeConfigTable>("cfg_quality_upgrade", v => { QualityUpgrade = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<RandomClubIconConfigTable>("cfg_random_club_icon", v => { RandomClubIcon = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<RandomClubNameConfigTable>("cfg_random_club_name", v => { RandomClubName = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<RandomRobotNameConfigTable>("cfg_random_robot_name", v => { RandomRobotName = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SeparatedPositionConfigTable>("cfg_separated_position", v => { SeparatedPosition = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SevenDayLoginRewardConfigTable>("cfg_seven_day_login_reward", v => { SevenDayLoginReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ShootGameAddedRewardConfigTable>("cfg_shoot_game_added_reward", v => { ShootGameAddedReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<ShootGameStageConfigTable>("cfg_shoot_game_stage", v => { ShootGameStage = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SkillConfigTable>("cfg_skill", v => { Skill = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SkillAdditionConfigTable>("cfg_skill_addition", v => { SkillAddition = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SkillUpgradeConfigTable>("cfg_skill_upgrade", v => { SkillUpgrade = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<StrengthenConfigTable>("cfg_strengthen", v => { Strengthen = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SysFormationConfigTable>("cfg_sys_formation", v => { SysFormation = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<SysTacticsConfigTable>("cfg_sys_tactics", v => { SysTactics = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TacticsConfigTable>("cfg_tactics", v => { Tactics = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TacticsTypeConfigTable>("cfg_tactics_type", v => { TacticsType = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TacticsUpgradeConfigTable>("cfg_tactics_upgrade", v => { TacticsUpgrade = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TaskConfigTable>("cfg_task", v => { Task = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TaskDemandConfigTable>("cfg_task_demand", v => { TaskDemand = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TaskRewardBoxConfigTable>("cfg_task_reward_box", v => { TaskRewardBox = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TowerConfigTable>("cfg_tower", v => { Tower = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TowerChapterConfigTable>("cfg_tower_chapter", v => { TowerChapter = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TowerStarRewardConfigTable>("cfg_tower_star_reward", v => { TowerStarReward = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TrainConfigTable>("cfg_train", v => { Train = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TrainShopConfigTable>("cfg_train_shop", v => { TrainShop = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<TriggerConfigTable>("cfg_trigger", v => { Trigger = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<UnitConfigTable>("cfg_unit", v => { Unit = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<UserLevelConfigTable>("cfg_user_level", v => { UserLevel = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<WayOfDescConfigTable>("cfg_way_of_desc", v => { WayOfDesc = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<WayOfGainConfigTable>("cfg_way_of_gain", v => { WayOfGain = v; --LeftCount; });
            ConfigManager.Instance.LoadTableAsync<WishSignConfigTable>("cfg_wish_sign", v => { WishSign = v; --LeftCount; });
            return System.Threading.Tasks.Task.CompletedTask;
        }
    }
}
