// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ModuleDevelop.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from ModuleDevelop.proto</summary>
  public static partial class ModuleDevelopReflection {

    #region Descriptor
    /// <summary>File descriptor for ModuleDevelop.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModuleDevelopReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNNb2R1bGVEZXZlbG9wLnByb3RvEghQcm90b2NvbCJrCg5EZXZlbG9wUmVx",
            "dWVzdBIpCgdjb21tYW5kGAEgASgOMhguUHJvdG9jb2wuRGV2ZWxvcENvbW1h",
            "bmQSDgoGcGFyYW0xGAIgASgJEg4KBnBhcmFtMhgDIAEoCRIOCgZwYXJhbTMY",
            "BCABKAkibAoPRGV2ZWxvcFJlc3BvbnNlEikKB2NvbW1hbmQYASABKA4yGC5Q",
            "cm90b2NvbC5EZXZlbG9wQ29tbWFuZBIOCgZwYXJhbTEYAiABKAkSDgoGcGFy",
            "YW0yGAMgASgJEg4KBnBhcmFtMxgEIAEoCSqeAgoORGV2ZWxvcENvbW1hbmQS",
            "CAoETm9uZRAAEg8KC2FkZEdhbWVJdGVtEAESFgoSY2xlYXJJbnZpdGVNYXRj",
            "aENEEAISEgoOY2xlYXJCaWdiYW5nQ0QQAxIRCg1zZXRUcmFpbkxldmVsEAQS",
            "DgoKc2V0RXhwVW5pdBAFEhAKDGNsZWFyQWNjb3VudBAGEhAKDGRhaWx5UmVm",
            "cmVzaBAHEhQKEG1vbnRoU2lnblJlZnJlc2gQCBIZChV1bmxvY2tTdHJlbmd0",
            "aGVuQmF0Y2gQCRIOCgp1bmxvY2tXaXNoEAoSFQoRdW5sb2NrSW52aXRlTWF0",
            "Y2gQCxISCg5zZXRDaGFsbGVuZ2VJRBAMEhIKDmFkZEFsbEdhbWVJdGVtEA1i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.DevelopCommand), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.DevelopRequest), global::Protocol.DevelopRequest.Parser, new[]{ "Command", "Param1", "Param2", "Param3" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Protocol.DevelopResponse), global::Protocol.DevelopResponse.Parser, new[]{ "Command", "Param1", "Param2", "Param3" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DevelopCommand {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("addGameItem")] AddGameItem = 1,
    [pbr::OriginalName("clearInviteMatchCD")] ClearInviteMatchCd = 2,
    [pbr::OriginalName("clearBigbangCD")] ClearBigbangCd = 3,
    [pbr::OriginalName("setTrainLevel")] SetTrainLevel = 4,
    [pbr::OriginalName("setExpUnit")] SetExpUnit = 5,
    [pbr::OriginalName("clearAccount")] ClearAccount = 6,
    [pbr::OriginalName("dailyRefresh")] DailyRefresh = 7,
    [pbr::OriginalName("monthSignRefresh")] MonthSignRefresh = 8,
    [pbr::OriginalName("unlockStrengthenBatch")] UnlockStrengthenBatch = 9,
    [pbr::OriginalName("unlockWish")] UnlockWish = 10,
    [pbr::OriginalName("unlockInviteMatch")] UnlockInviteMatch = 11,
    [pbr::OriginalName("setChallengeID")] SetChallengeId = 12,
    [pbr::OriginalName("addAllGameItem")] AddAllGameItem = 13,
  }

  #endregion

  #region Messages
  /// <summary>
  ///--指令
  ///cs:develop_module.cs_developCommand
  /// </summary>
  public sealed partial class DevelopRequest : pb::IMessage<DevelopRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DevelopRequest> _parser = new pb::MessageParser<DevelopRequest>(() => new DevelopRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DevelopRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ModuleDevelopReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopRequest(DevelopRequest other) : this() {
      command_ = other.command_;
      param1_ = other.param1_;
      param2_ = other.param2_;
      param3_ = other.param3_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopRequest Clone() {
      return new DevelopRequest(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private global::Protocol.DevelopCommand command_ = global::Protocol.DevelopCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.DevelopCommand Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "param1" field.</summary>
    public const int Param1FieldNumber = 2;
    private string param1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param1 {
      get { return param1_; }
      set {
        param1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param2" field.</summary>
    public const int Param2FieldNumber = 3;
    private string param2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param2 {
      get { return param2_; }
      set {
        param2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param3" field.</summary>
    public const int Param3FieldNumber = 4;
    private string param3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param3 {
      get { return param3_; }
      set {
        param3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DevelopRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DevelopRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      if (Param1 != other.Param1) return false;
      if (Param2 != other.Param2) return false;
      if (Param3 != other.Param3) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Command != global::Protocol.DevelopCommand.None) hash ^= Command.GetHashCode();
      if (Param1.Length != 0) hash ^= Param1.GetHashCode();
      if (Param2.Length != 0) hash ^= Param2.GetHashCode();
      if (Param3.Length != 0) hash ^= Param3.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Command != global::Protocol.DevelopCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Command != global::Protocol.DevelopCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Command != global::Protocol.DevelopCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (Param1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param1);
      }
      if (Param2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param2);
      }
      if (Param3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param3);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DevelopRequest other) {
      if (other == null) {
        return;
      }
      if (other.Command != global::Protocol.DevelopCommand.None) {
        Command = other.Command;
      }
      if (other.Param1.Length != 0) {
        Param1 = other.Param1;
      }
      if (other.Param2.Length != 0) {
        Param2 = other.Param2;
      }
      if (other.Param3.Length != 0) {
        Param3 = other.Param3;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Command = (global::Protocol.DevelopCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Command = (global::Protocol.DevelopCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DevelopResponse : pb::IMessage<DevelopResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DevelopResponse> _parser = new pb::MessageParser<DevelopResponse>(() => new DevelopResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DevelopResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Protocol.ModuleDevelopReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopResponse(DevelopResponse other) : this() {
      command_ = other.command_;
      param1_ = other.param1_;
      param2_ = other.param2_;
      param3_ = other.param3_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DevelopResponse Clone() {
      return new DevelopResponse(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 1;
    private global::Protocol.DevelopCommand command_ = global::Protocol.DevelopCommand.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Protocol.DevelopCommand Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    /// <summary>Field number for the "param1" field.</summary>
    public const int Param1FieldNumber = 2;
    private string param1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param1 {
      get { return param1_; }
      set {
        param1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param2" field.</summary>
    public const int Param2FieldNumber = 3;
    private string param2_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param2 {
      get { return param2_; }
      set {
        param2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "param3" field.</summary>
    public const int Param3FieldNumber = 4;
    private string param3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Param3 {
      get { return param3_; }
      set {
        param3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DevelopResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DevelopResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Command != other.Command) return false;
      if (Param1 != other.Param1) return false;
      if (Param2 != other.Param2) return false;
      if (Param3 != other.Param3) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Command != global::Protocol.DevelopCommand.None) hash ^= Command.GetHashCode();
      if (Param1.Length != 0) hash ^= Param1.GetHashCode();
      if (Param2.Length != 0) hash ^= Param2.GetHashCode();
      if (Param3.Length != 0) hash ^= Param3.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Command != global::Protocol.DevelopCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Command != global::Protocol.DevelopCommand.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Command);
      }
      if (Param1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Param1);
      }
      if (Param2.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Param2);
      }
      if (Param3.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Param3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Command != global::Protocol.DevelopCommand.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (Param1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param1);
      }
      if (Param2.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param2);
      }
      if (Param3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Param3);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DevelopResponse other) {
      if (other == null) {
        return;
      }
      if (other.Command != global::Protocol.DevelopCommand.None) {
        Command = other.Command;
      }
      if (other.Param1.Length != 0) {
        Param1 = other.Param1;
      }
      if (other.Param2.Length != 0) {
        Param2 = other.Param2;
      }
      if (other.Param3.Length != 0) {
        Param3 = other.Param3;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Command = (global::Protocol.DevelopCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Command = (global::Protocol.DevelopCommand) input.ReadEnum();
            break;
          }
          case 18: {
            Param1 = input.ReadString();
            break;
          }
          case 26: {
            Param2 = input.ReadString();
            break;
          }
          case 34: {
            Param3 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
