
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class AchievementConfig : ConfigBase
    {
        public int Fungroup { get; private set; }
        public int Type { get; private set; }
        public int Icon { get; private set; }
        public string Name { get; private set; }
        public string Desc { get; private set; }
        public string Reward { get; private set; }
        public int[] Target { get; private set; }
        public int Point { get; private set; }
        public int ClientCheck { get; private set; }
        public int Moduleid { get; private set; }
        public string Info { get; private set; }
        public int IsHide { get; private set; }
        public int Module { get; private set; }
        public int CanAdd { get; private set; }
        public int ClientGroup { get; private set; }
        public string GroupTitle { get; private set; }
        public int MaxShowTimes { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Fungroup = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            Target = ByteConfigReader.GetInt32Array(binaryReader);
            Point = ByteConfigReader.GetInt32(binaryReader);
            ClientCheck = ByteConfigReader.GetInt32(binaryReader);
            Moduleid = ByteConfigReader.GetInt32(binaryReader);
            Info = ByteConfigReader.GetString(binaryReader);
            IsHide = ByteConfigReader.GetInt32(binaryReader);
            Module = ByteConfigReader.GetInt32(binaryReader);
            CanAdd = ByteConfigReader.GetInt32(binaryReader);
            ClientGroup = ByteConfigReader.GetInt32(binaryReader);
            GroupTitle = ByteConfigReader.GetString(binaryReader);
            MaxShowTimes = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class AchievementConfigTable : IdentityConfigTable<AchievementConfig> { }
}

