
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ActivityBattlePassRewardConfig : ConfigBase
    {
        public int ActivityId { get; private set; }
        public int Option { get; private set; }
        public int Exp { get; private set; }
        public string Rewards1 { get; private set; }
        public string Rewards2 { get; private set; }
        public string RewardsStep { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ActivityId = ByteConfigReader.GetInt32(binaryReader);
            Option = ByteConfigReader.GetInt32(binaryReader);
            Exp = ByteConfigReader.GetInt32(binaryReader);
            Rewards1 = ByteConfigReader.GetString(binaryReader);
            Rewards2 = ByteConfigReader.GetString(binaryReader);
            RewardsStep = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ActivityBattlePassRewardConfigTable : IdentityConfigTable<ActivityBattlePassRewardConfig> { }
}

