
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ActivityTopRewardConfig : ConfigBase
    {
        public int ActivityId { get; private set; }
        public int Min { get; private set; }
        public int Max { get; private set; }
        public string Rewards { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ActivityId = ByteConfigReader.GetInt32(binaryReader);
            Min = ByteConfigReader.GetInt32(binaryReader);
            Max = ByteConfigReader.GetInt32(binaryReader);
            Rewards = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ActivityTopRewardConfigTable : IdentityConfigTable<ActivityTopRewardConfig> { }
}

