
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ActivityConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Type { get; private set; }
        public int ClientType { get; private set; }
        public int Point { get; private set; }
        public int ServerDays { get; private set; }
        public int StartTime { get; private set; }
        public int LastTime { get; private set; }
        public int ServerFilter { get; private set; }
        public int RewardTime { get; private set; }
        public int LoopTime { get; private set; }
        public string DailyGift { get; private set; }
        public string DailyGiftDesc { get; private set; }
        public int Param1 { get; private set; }
        public string Param2 { get; private set; }
        public string Param3 { get; private set; }
        public string Pic { get; private set; }
        public int JumpGroup { get; private set; }
        public string HomeTitle { get; private set; }
        public string HomeSubTitle { get; private set; }
        public string ToggleIcon { get; private set; }
        public int ShowInActivity { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            ClientType = ByteConfigReader.GetInt32(binaryReader);
            Point = ByteConfigReader.GetInt32(binaryReader);
            ServerDays = ByteConfigReader.GetInt32(binaryReader);
            StartTime = ByteConfigReader.GetInt32(binaryReader);
            LastTime = ByteConfigReader.GetInt32(binaryReader);
            ServerFilter = ByteConfigReader.GetInt32(binaryReader);
            RewardTime = ByteConfigReader.GetInt32(binaryReader);
            LoopTime = ByteConfigReader.GetInt32(binaryReader);
            DailyGift = ByteConfigReader.GetString(binaryReader);
            DailyGiftDesc = ByteConfigReader.GetString(binaryReader);
            Param1 = ByteConfigReader.GetInt32(binaryReader);
            Param2 = ByteConfigReader.GetString(binaryReader);
            Param3 = ByteConfigReader.GetString(binaryReader);
            Pic = ByteConfigReader.GetString(binaryReader);
            JumpGroup = ByteConfigReader.GetInt32(binaryReader);
            HomeTitle = ByteConfigReader.GetString(binaryReader);
            HomeSubTitle = ByteConfigReader.GetString(binaryReader);
            ToggleIcon = ByteConfigReader.GetString(binaryReader);
            ShowInActivity = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class ActivityConfigTable : IdentityConfigTable<ActivityConfig> { }
}

