
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class AllStarAdditionConfig : ConfigBase
    {
        public int Type { get; private set; }
        public float Addition { get; private set; }
        public int Area { get; private set; }
        public int[] AdaptPosition { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Addition = ByteConfigReader.GetFloat32(binaryReader);
            Area = ByteConfigReader.GetInt32(binaryReader);
            AdaptPosition = ByteConfigReader.GetInt32Array(binaryReader);
        }
    }
    
    public class AllStarAdditionConfigTable : IdentityConfigTable<AllStarAdditionConfig> { }
}

