
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ArenaRewardConfig : ConfigBase
    {
        public int Type { get; private set; }
        public int Stage { get; private set; }
        public int RankMin { get; private set; }
        public int RankMax { get; private set; }
        public string Reward { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Stage = ByteConfigReader.GetInt32(binaryReader);
            RankMin = ByteConfigReader.GetInt32(binaryReader);
            RankMax = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ArenaRewardConfigTable : IdentityConfigTable<ArenaRewardConfig> { }
}

