
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ArenaBattleResultConfig : ConfigBase
    {
        public int Result { get; private set; }
        public string Desc { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Result = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ArenaBattleResultConfigTable : IdentityConfigTable<ArenaBattleResultConfig> { }
}

