
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ArenaShopConfig : ConfigBase
    {
        public string Item { get; private set; }
        public int Cost { get; private set; }
        public int Stage { get; private set; }
        public int Limit { get; private set; }
        public int WeekLimit { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Item = ByteConfigReader.GetString(binaryReader);
            Cost = ByteConfigReader.GetInt32(binaryReader);
            Stage = ByteConfigReader.GetInt32(binaryReader);
            Limit = ByteConfigReader.GetInt32(binaryReader);
            WeekLimit = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class ArenaShopConfigTable : IdentityConfigTable<ArenaShopConfig> { }
}

