
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ArenaPlayerConfig : ConfigBase
    {
        public int CardId { get; private set; }
        public int Star { get; private set; }
        public int ClubId { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> Ability { get; private set; }
        public int Position { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            CardId = ByteConfigReader.GetInt32(binaryReader);
            Star = ByteConfigReader.GetInt32(binaryReader);
            ClubId = ByteConfigReader.GetInt32(binaryReader);
            Ability = ByteConfigReader.GetIntIntDic(binaryReader);
            Position = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class ArenaPlayerConfigTable : IdentityConfigTable<ArenaPlayerConfig> { }
}

