
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ArenaClubConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Icon { get; private set; }
        public int[] Tactics { get; private set; }
        public int[] TacticsLevels { get; private set; }
        public int Formation { get; private set; }
        public int Strength { get; private set; }
        public int RankStage { get; private set; }
        public int Score { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Tactics = ByteConfigReader.GetInt32Array(binaryReader);
            TacticsLevels = ByteConfigReader.GetInt32Array(binaryReader);
            Formation = ByteConfigReader.GetInt32(binaryReader);
            Strength = ByteConfigReader.GetInt32(binaryReader);
            RankStage = ByteConfigReader.GetInt32(binaryReader);
            Score = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class ArenaClubConfigTable : IdentityConfigTable<ArenaClubConfig> { }
}

