
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class BountyTaskConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string Icon { get; private set; }
        public int Time { get; private set; }
        public int Hero { get; private set; }
        public int[] OnBattle { get; private set; }
        public string Rewards { get; private set; }
        public string Desc { get; private set; }
        public string Option { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetString(binaryReader);
            Time = ByteConfigReader.GetInt32(binaryReader);
            Hero = ByteConfigReader.GetInt32(binaryReader);
            OnBattle = ByteConfigReader.GetInt32Array(binaryReader);
            Rewards = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Option = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class BountyTaskConfigTable : IdentityConfigTable<BountyTaskConfig> { }
}

