
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class BoxConfig : ConfigBase
    {
        public int BoxId { get; private set; }
        public int Group { get; private set; }
        public int RewardType { get; private set; }
        public int RewardId { get; private set; }
        public int RewardNum { get; private set; }
        public int Weight { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            BoxId = ByteConfigReader.GetInt32(binaryReader);
            Group = ByteConfigReader.GetInt32(binaryReader);
            RewardType = ByteConfigReader.GetInt32(binaryReader);
            RewardId = ByteConfigReader.GetInt32(binaryReader);
            RewardNum = ByteConfigReader.GetInt32(binaryReader);
            Weight = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class BoxConfigTable : IdentityConfigTable<BoxConfig> { }
}

