
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class BreakConfig : ConfigBase
    {
        public int TrainId { get; private set; }
        public int BreakIndex { get; private set; }
        public int TargetLevel { get; private set; }
        public int BuffType { get; private set; }
        public float BuffValue { get; private set; }
        public int CardBuffType { get; private set; }
        public float CardBuffValue { get; private set; }
        public float CardTotalValue { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            TrainId = ByteConfigReader.GetInt32(binaryReader);
            BreakIndex = ByteConfigReader.GetInt32(binaryReader);
            TargetLevel = ByteConfigReader.GetInt32(binaryReader);
            BuffType = ByteConfigReader.GetInt32(binaryReader);
            BuffValue = ByteConfigReader.GetFloat32(binaryReader);
            CardBuffType = ByteConfigReader.GetInt32(binaryReader);
            CardBuffValue = ByteConfigReader.GetFloat32(binaryReader);
            CardTotalValue = ByteConfigReader.GetFloat32(binaryReader);
        }
    }
    
    public class BreakConfigTable : IdentityConfigTable<BreakConfig> { }
}

