
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardPoolInfoConfig : ConfigBase
    {
        public string Desc { get; private set; }
        public int SeniorQuality { get; private set; }
        public int FloorsCount { get; private set; }
        public int CostGoods { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            SeniorQuality = ByteConfigReader.GetInt32(binaryReader);
            FloorsCount = ByteConfigReader.GetInt32(binaryReader);
            CostGoods = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class CardPoolInfoConfigTable : IdentityConfigTable<CardPoolInfoConfig> { }
}

