
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardUpgradeConfig : ConfigBase
    {
        public int CardId { get; private set; }
        public int Quality { get; private set; }
        public int Star { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> AbilityAdd { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> Sklv { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> AbilityRatio { get; private set; }
        public int Power { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            CardId = ByteConfigReader.GetInt32(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            Star = ByteConfigReader.GetInt32(binaryReader);
            AbilityAdd = ByteConfigReader.GetIntIntDic(binaryReader);
            Sklv = ByteConfigReader.GetIntIntDic(binaryReader);
            AbilityRatio = ByteConfigReader.GetIntIntDic(binaryReader);
            Power = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class CardUpgradeConfigTable : IdentityConfigTable<CardUpgradeConfig> { }
}

