
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardBuffTypeConfig : ConfigBase
    {
        public string Desc { get; private set; }
        public string DescPart1 { get; private set; }
        public string DescPart2 { get; private set; }
        public string DescOperator { get; private set; }
        public int EffectTrainId { get; private set; }
        public string TrainIconName { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            DescPart1 = ByteConfigReader.GetString(binaryReader);
            DescPart2 = ByteConfigReader.GetString(binaryReader);
            DescOperator = ByteConfigReader.GetString(binaryReader);
            EffectTrainId = ByteConfigReader.GetInt32(binaryReader);
            TrainIconName = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class CardBuffTypeConfigTable : IdentityConfigTable<CardBuffTypeConfig> { }
}

