
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardPoolGroupConfig : ConfigBase
    {
        public int PoolInfo { get; private set; }
        public string Desc { get; private set; }
        public string Operator { get; private set; }
        public int Operand { get; private set; }
        public int PoolId { get; private set; }
        public string Nxtinfo { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            PoolInfo = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Operator = ByteConfigReader.GetString(binaryReader);
            Operand = ByteConfigReader.GetInt32(binaryReader);
            PoolId = ByteConfigReader.GetInt32(binaryReader);
            Nxtinfo = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class CardPoolGroupConfigTable : IdentityConfigTable<CardPoolGroupConfig> { }
}

