
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardFireConfig : ConfigBase
    {
        public int Quality { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> ReturnGoods { get; private set; }
        public int ReturnPercent { get; private set; }
        public int Money { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            ReturnGoods = ByteConfigReader.GetIntIntDic(binaryReader);
            ReturnPercent = ByteConfigReader.GetInt32(binaryReader);
            Money = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class CardFireConfigTable : IdentityConfigTable<CardFireConfig> { }
}

