
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardPoolConfig : ConfigBase
    {
        public int PoolId { get; private set; }
        public int CardId { get; private set; }
        public int Weight { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            PoolId = ByteConfigReader.GetInt32(binaryReader);
            CardId = ByteConfigReader.GetInt32(binaryReader);
            Weight = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class CardPoolConfigTable : IdentityConfigTable<CardPoolConfig> { }
}

