
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CardModelConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Portrait { get; private set; }
        public int CardYellowBg { get; private set; }
        public int Height { get; private set; }
        public int Weight { get; private set; }
        public int Nationality { get; private set; }
        public int Position { get; private set; }
        public int[] AdaptPosition { get; private set; }
        public int Number { get; private set; }
        public int Quality { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> Ability { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> AbilityRatio { get; private set; }
        public int ExtraAbility { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> PositionRatio { get; private set; }
        public int PiecesId { get; private set; }
        public int PiecesCount { get; private set; }
        public int[] Skills { get; private set; }
        public int ExtractWeight { get; private set; }
        public int[] GiftIds { get; private set; }
        public string Desc { get; private set; }
        public string Param { get; private set; }
        public int Power { get; private set; }
        public string RecruitWords { get; private set; }
        public int IsRetire { get; private set; }
        public string PeakYear { get; private set; }
        public string PeakLogo { get; private set; }
        public int Sale { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Portrait = ByteConfigReader.GetInt32(binaryReader);
            CardYellowBg = ByteConfigReader.GetInt32(binaryReader);
            Height = ByteConfigReader.GetInt32(binaryReader);
            Weight = ByteConfigReader.GetInt32(binaryReader);
            Nationality = ByteConfigReader.GetInt32(binaryReader);
            Position = ByteConfigReader.GetInt32(binaryReader);
            AdaptPosition = ByteConfigReader.GetInt32Array(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            Ability = ByteConfigReader.GetIntIntDic(binaryReader);
            AbilityRatio = ByteConfigReader.GetIntIntDic(binaryReader);
            ExtraAbility = ByteConfigReader.GetInt32(binaryReader);
            PositionRatio = ByteConfigReader.GetIntIntDic(binaryReader);
            PiecesId = ByteConfigReader.GetInt32(binaryReader);
            PiecesCount = ByteConfigReader.GetInt32(binaryReader);
            Skills = ByteConfigReader.GetInt32Array(binaryReader);
            ExtractWeight = ByteConfigReader.GetInt32(binaryReader);
            GiftIds = ByteConfigReader.GetInt32Array(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Param = ByteConfigReader.GetString(binaryReader);
            Power = ByteConfigReader.GetInt32(binaryReader);
            RecruitWords = ByteConfigReader.GetString(binaryReader);
            IsRetire = ByteConfigReader.GetInt32(binaryReader);
            PeakYear = ByteConfigReader.GetString(binaryReader);
            PeakLogo = ByteConfigReader.GetString(binaryReader);
            Sale = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class CardModelConfigTable : IdentityConfigTable<CardModelConfig> { }
}

