
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengeClubConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Icon { get; private set; }
        public int Country { get; private set; }
        public int[] Tactics { get; private set; }
        public int[] TacticsLevels { get; private set; }
        public string FirstReward { get; private set; }
        public string Reward { get; private set; }
        public int Count { get; private set; }
        public int[] Star3 { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Country = ByteConfigReader.GetInt32(binaryReader);
            Tactics = ByteConfigReader.GetInt32Array(binaryReader);
            TacticsLevels = ByteConfigReader.GetInt32Array(binaryReader);
            FirstReward = ByteConfigReader.GetString(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            Count = ByteConfigReader.GetInt32(binaryReader);
            Star3 = ByteConfigReader.GetInt32Array(binaryReader);
        }
    }
    
    public class ChallengeClubConfigTable : IdentityConfigTable<ChallengeClubConfig> { }
}

