
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengeCountryConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string Des { get; private set; }
        public int UserLevel { get; private set; }
        public int Level { get; private set; }
        public int Map { get; private set; }
        public string LevelTxt { get; private set; }
        public int Number { get; private set; }
        public int Star1 { get; private set; }
        public string Reward1 { get; private set; }
        public int Star2 { get; private set; }
        public string Reward2 { get; private set; }
        public int Star3 { get; private set; }
        public string Reward3 { get; private set; }
        public int Unlock { get; private set; }
        public string Icon { get; private set; }
        public string NodeName { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Des = ByteConfigReader.GetString(binaryReader);
            UserLevel = ByteConfigReader.GetInt32(binaryReader);
            Level = ByteConfigReader.GetInt32(binaryReader);
            Map = ByteConfigReader.GetInt32(binaryReader);
            LevelTxt = ByteConfigReader.GetString(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
            Star1 = ByteConfigReader.GetInt32(binaryReader);
            Reward1 = ByteConfigReader.GetString(binaryReader);
            Star2 = ByteConfigReader.GetInt32(binaryReader);
            Reward2 = ByteConfigReader.GetString(binaryReader);
            Star3 = ByteConfigReader.GetInt32(binaryReader);
            Reward3 = ByteConfigReader.GetString(binaryReader);
            Unlock = ByteConfigReader.GetInt32(binaryReader);
            Icon = ByteConfigReader.GetString(binaryReader);
            NodeName = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ChallengeCountryConfigTable : IdentityConfigTable<ChallengeCountryConfig> { }
}

