
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengePlayerConfig : ConfigBase
    {
        public int Portrait { get; private set; }
        public int Star { get; private set; }
        public int[] Skills { get; private set; }
        public int ClubId { get; private set; }
        public string Name { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> Ability { get; private set; }
        public int Number { get; private set; }
        public int[] AdaptPosition { get; private set; }
        public int Quality { get; private set; }
        public int[] GiftIds { get; private set; }
        public int Power { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Portrait = ByteConfigReader.GetInt32(binaryReader);
            Star = ByteConfigReader.GetInt32(binaryReader);
            Skills = ByteConfigReader.GetInt32Array(binaryReader);
            ClubId = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Ability = ByteConfigReader.GetIntIntDic(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
            AdaptPosition = ByteConfigReader.GetInt32Array(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            GiftIds = ByteConfigReader.GetInt32Array(binaryReader);
            Power = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class ChallengePlayerConfigTable : IdentityConfigTable<ChallengePlayerConfig> { }
}

