
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengeRuleConfig : ConfigBase
    {
        public string Action { get; private set; }
        public string Key { get; private set; }
        public int KeyValue { get; private set; }
        public string Judge { get; private set; }
        public int Value { get; private set; }
        public string Desc { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Action = ByteConfigReader.GetString(binaryReader);
            Key = ByteConfigReader.GetString(binaryReader);
            KeyValue = ByteConfigReader.GetInt32(binaryReader);
            Judge = ByteConfigReader.GetString(binaryReader);
            Value = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ChallengeRuleConfigTable : IdentityConfigTable<ChallengeRuleConfig> { }
}

