
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengeHeroChapterConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Hero { get; private set; }
        public int Star { get; private set; }
        public int Prev { get; private set; }
        public string Des { get; private set; }
        public int Number { get; private set; }
        public int Star1 { get; private set; }
        public string Reward1 { get; private set; }
        public int Star2 { get; private set; }
        public string Reward2 { get; private set; }
        public int Star3 { get; private set; }
        public string Reward3 { get; private set; }
        public string Showrewards { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Hero = ByteConfigReader.GetInt32(binaryReader);
            Star = ByteConfigReader.GetInt32(binaryReader);
            Prev = ByteConfigReader.GetInt32(binaryReader);
            Des = ByteConfigReader.GetString(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
            Star1 = ByteConfigReader.GetInt32(binaryReader);
            Reward1 = ByteConfigReader.GetString(binaryReader);
            Star2 = ByteConfigReader.GetInt32(binaryReader);
            Reward2 = ByteConfigReader.GetString(binaryReader);
            Star3 = ByteConfigReader.GetInt32(binaryReader);
            Reward3 = ByteConfigReader.GetString(binaryReader);
            Showrewards = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ChallengeHeroChapterConfigTable : IdentityConfigTable<ChallengeHeroChapterConfig> { }
}

