
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ChallengeMapConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string NodeName { get; private set; }
        public string IconUI { get; private set; }
        public string IconNew { get; private set; }
        public string ScenePrefab { get; private set; }
        public string Des { get; private set; }
        public int Level { get; private set; }
        public string LevelTxt { get; private set; }
        public string IdleAnim { get; private set; }
        public string TransferAnim { get; private set; }
        public int Next { get; private set; }
        public int Number { get; private set; }
        public int Order { get; private set; }
        public string Icon3D { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            NodeName = ByteConfigReader.GetString(binaryReader);
            IconUI = ByteConfigReader.GetString(binaryReader);
            IconNew = ByteConfigReader.GetString(binaryReader);
            ScenePrefab = ByteConfigReader.GetString(binaryReader);
            Des = ByteConfigReader.GetString(binaryReader);
            Level = ByteConfigReader.GetInt32(binaryReader);
            LevelTxt = ByteConfigReader.GetString(binaryReader);
            IdleAnim = ByteConfigReader.GetString(binaryReader);
            TransferAnim = ByteConfigReader.GetString(binaryReader);
            Next = ByteConfigReader.GetInt32(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
            Order = ByteConfigReader.GetInt32(binaryReader);
            Icon3D = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ChallengeMapConfigTable : IdentityConfigTable<ChallengeMapConfig> { }
}

