
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class CommonTriggerConfig : ConfigBase
    {
        public int TriggerId { get; private set; }
        public string CompareType { get; private set; }
        public int Condition { get; private set; }
        public string Action { get; private set; }
        public string ActionParam { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            TriggerId = ByteConfigReader.GetInt32(binaryReader);
            CompareType = ByteConfigReader.GetString(binaryReader);
            Condition = ByteConfigReader.GetInt32(binaryReader);
            Action = ByteConfigReader.GetString(binaryReader);
            ActionParam = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class CommonTriggerConfigTable : IdentityConfigTable<CommonTriggerConfig> { }
}

