
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class DiamondShopConfig : ConfigBase
    {
        public string ProductId { get; private set; }
        public int Obtain { get; private set; }
        public string Name { get; private set; }
        public int Give { get; private set; }
        public float Rmb { get; private set; }
        public float Dollar { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ProductId = ByteConfigReader.GetString(binaryReader);
            Obtain = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Give = ByteConfigReader.GetInt32(binaryReader);
            Rmb = ByteConfigReader.GetFloat32(binaryReader);
            Dollar = ByteConfigReader.GetFloat32(binaryReader);
        }
    }
    
    public class DiamondShopConfigTable : IdentityConfigTable<DiamondShopConfig> { }
}

