
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class EnergyTimeLimitConfig : ConfigBase
    {
        public int MinTime { get; private set; }
        public int MaxTime { get; private set; }
        public string Rewards { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            MinTime = ByteConfigReader.GetInt32(binaryReader);
            MaxTime = ByteConfigReader.GetInt32(binaryReader);
            Rewards = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class EnergyTimeLimitConfigTable : IdentityConfigTable<EnergyTimeLimitConfig> { }
}

