
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ExampleConfig : ConfigBase
    {
        public string Name { get; private set; }
        public float FloatEx { get; private set; }
        public int[] ExIntList { get; private set; }
        public string[] ExStringList { get; private set; }
        public float[] ExFloatList { get; private set; }
        public System.Collections.Generic.Dictionary<int, string> ExIntStringDic { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> ExIntIntDic { get; private set; }
        public System.Collections.Generic.Dictionary<string, int> ExStringIntDic { get; private set; }
        public System.Collections.Generic.Dictionary<int, float> ExIntFloatDic { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            FloatEx = ByteConfigReader.GetFloat32(binaryReader);
            ExIntList = ByteConfigReader.GetInt32Array(binaryReader);
            ExStringList = ByteConfigReader.GetStringArray(binaryReader);
            ExFloatList = ByteConfigReader.GetFloat32Array(binaryReader);
            ExIntStringDic = ByteConfigReader.GetIntStringDic(binaryReader);
            ExIntIntDic = ByteConfigReader.GetIntIntDic(binaryReader);
            ExStringIntDic = ByteConfigReader.GetStringIntDic(binaryReader);
            ExIntFloatDic = ByteConfigReader.GetIntFloatDic(binaryReader);
        }
    }
    
    public class ExampleConfigTable : IdentityConfigTable<ExampleConfig> { }
}

