
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FestivalTravelConfig : ConfigBase
    {
        public int ActivityId { get; private set; }
        public string Reward { get; private set; }
        public int Order { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ActivityId = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            Order = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class FestivalTravelConfigTable : IdentityConfigTable<FestivalTravelConfig> { }
}

