
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FestivalLoginConfig : ConfigBase
    {
        public int ActivityId { get; private set; }
        public int Option { get; private set; }
        public string Content { get; private set; }
        public string Rewards { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ActivityId = ByteConfigReader.GetInt32(binaryReader);
            Option = ByteConfigReader.GetInt32(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            Rewards = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class FestivalLoginConfigTable : IdentityConfigTable<FestivalLoginConfig> { }
}

