
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FestivalBoxConfig : ConfigBase
    {
        public int BoxId { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> GuaranteeBoxes { get; private set; }
        public int KeyId { get; private set; }
        public int BatchCount { get; private set; }
        public int FestivalTaskActivity { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            BoxId = ByteConfigReader.GetInt32(binaryReader);
            GuaranteeBoxes = ByteConfigReader.GetIntIntDic(binaryReader);
            KeyId = ByteConfigReader.GetInt32(binaryReader);
            BatchCount = ByteConfigReader.GetInt32(binaryReader);
            FestivalTaskActivity = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class FestivalBoxConfigTable : IdentityConfigTable<FestivalBoxConfig> { }
}

