
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FightStatConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int ProMax { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            ProMax = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class FightStatConfigTable : IdentityConfigTable<FightStatConfig> { }
}

