
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FinalsGuessCourseConfig : ConfigBase
    {
        public int MatchTime { get; private set; }
        public int HomeTeam { get; private set; }
        public int AwayTeam { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            MatchTime = ByteConfigReader.GetInt32(binaryReader);
            HomeTeam = ByteConfigReader.GetInt32(binaryReader);
            AwayTeam = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class FinalsGuessCourseConfigTable : IdentityConfigTable<FinalsGuessCourseConfig> { }
}

