
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FinalsGuessPlayerConfig : ConfigBase
    {
        public int Team { get; private set; }
        public string Name { get; private set; }
        public int Icon { get; private set; }
        public int Position { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Team = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Position = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class FinalsGuessPlayerConfigTable : IdentityConfigTable<FinalsGuessPlayerConfig> { }
}

