
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class FinalsGuessRewardConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string SuccessReward { get; private set; }
        public string FailReward { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            SuccessReward = ByteConfigReader.GetString(binaryReader);
            FailReward = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class FinalsGuessRewardConfigTable : IdentityConfigTable<FinalsGuessRewardConfig> { }
}

