
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GameItemShopConfig : ConfigBase
    {
        public int Type { get; private set; }
        public string Item { get; private set; }
        public string Cost { get; private set; }
        public int DayLimit { get; private set; }
        public int WeekLimit { get; private set; }
        public int SeasonLimit { get; private set; }
        public int Limit { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Item = ByteConfigReader.GetString(binaryReader);
            Cost = ByteConfigReader.GetString(binaryReader);
            DayLimit = ByteConfigReader.GetInt32(binaryReader);
            WeekLimit = ByteConfigReader.GetInt32(binaryReader);
            SeasonLimit = ByteConfigReader.GetInt32(binaryReader);
            Limit = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class GameItemShopConfigTable : IdentityConfigTable<GameItemShopConfig> { }
}

