
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GameBroadcastConfig : ConfigBase
    {
        public int EventId { get; private set; }
        public int Weight { get; private set; }
        public string Content { get; private set; }
        public string GroupContent { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            EventId = ByteConfigReader.GetInt32(binaryReader);
            Weight = ByteConfigReader.GetInt32(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            GroupContent = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class GameBroadcastConfigTable : IdentityConfigTable<GameBroadcastConfig> { }
}

