
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GiftShopConfig : ConfigBase
    {
        public int Type { get; private set; }
        public string Subtitle { get; private set; }
        public string ProductId { get; private set; }
        public string Content { get; private set; }
        public int DailyLimit { get; private set; }
        public int Limit { get; private set; }
        public float Rmb { get; private set; }
        public float Dollar { get; private set; }
        public string Pic { get; private set; }
        public int Pos { get; private set; }
        public string Param { get; private set; }
        public int Rebate { get; private set; }

        private string __Name;
        public string Name 
        { 
            get => Babu.Globalization.Globalizer.Instance.GetGlobalizationText(__Name);
            private set => __Name = value; 
        }

        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Subtitle = ByteConfigReader.GetString(binaryReader);
            ProductId = ByteConfigReader.GetString(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            DailyLimit = ByteConfigReader.GetInt32(binaryReader);
            Limit = ByteConfigReader.GetInt32(binaryReader);
            Rmb = ByteConfigReader.GetFloat32(binaryReader);
            Dollar = ByteConfigReader.GetFloat32(binaryReader);
            Pic = ByteConfigReader.GetString(binaryReader);
            Pos = ByteConfigReader.GetInt32(binaryReader);
            Param = ByteConfigReader.GetString(binaryReader);
            Rebate = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class GiftShopConfigTable : IdentityConfigTable<GiftShopConfig> { }
}

