
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GiftSkillConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string Icon { get; private set; }
        public int Skindex { get; private set; }
        public int Sklv { get; private set; }
        public string Action { get; private set; }
        public int[] Actparam { get; private set; }
        public string[] Actobj { get; private set; }
        public int Side { get; private set; }
        public string When { get; private set; }
        public int Wparam2 { get; private set; }
        public string Wparam1 { get; private set; }
        public int Bufftime { get; private set; }
        public int Time { get; private set; }
        public string Desc { get; private set; }
        public int Fire { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetString(binaryReader);
            Skindex = ByteConfigReader.GetInt32(binaryReader);
            Sklv = ByteConfigReader.GetInt32(binaryReader);
            Action = ByteConfigReader.GetString(binaryReader);
            Actparam = ByteConfigReader.GetInt32Array(binaryReader);
            Actobj = ByteConfigReader.GetStringArray(binaryReader);
            Side = ByteConfigReader.GetInt32(binaryReader);
            When = ByteConfigReader.GetString(binaryReader);
            Wparam2 = ByteConfigReader.GetInt32(binaryReader);
            Wparam1 = ByteConfigReader.GetString(binaryReader);
            Bufftime = ByteConfigReader.GetInt32(binaryReader);
            Time = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Fire = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class GiftSkillConfigTable : IdentityConfigTable<GiftSkillConfig> { }
}

