
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GoodsConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Icon { get; private set; }
        public string Desc { get; private set; }
        public int Quality { get; private set; }
        public int Type { get; private set; }
        public int Param1 { get; private set; }
        public int Param2 { get; private set; }
        public int Price { get; private set; }
        public long ExpirationTime { get; private set; }
        public int StackNum { get; private set; }
        public int Uselv { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Param1 = ByteConfigReader.GetInt32(binaryReader);
            Param2 = ByteConfigReader.GetInt32(binaryReader);
            Price = ByteConfigReader.GetInt32(binaryReader);
            ExpirationTime = ByteConfigReader.GetInt64(binaryReader);
            StackNum = ByteConfigReader.GetInt32(binaryReader);
            Uselv = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class GoodsConfigTable : IdentityConfigTable<GoodsConfig> { }
}

