
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GuideEmailConfig : ConfigBase
    {
        public string Title { get; private set; }
        public string Receiver { get; private set; }
        public string Sender { get; private set; }
        public string Content { get; private set; }
        public string Reward { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Title = ByteConfigReader.GetString(binaryReader);
            Receiver = ByteConfigReader.GetString(binaryReader);
            Sender = ByteConfigReader.GetString(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class GuideEmailConfigTable : IdentityConfigTable<GuideEmailConfig> { }
}

