
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class GuideDialogueConfig : ConfigBase
    {
        public int Character { get; private set; }
        public string Content { get; private set; }
        public string Next { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Character = ByteConfigReader.GetInt32(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            Next = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class GuideDialogueConfigTable : IdentityConfigTable<GuideDialogueConfig> { }
}

