
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class HundredPlayoffCourseConfig : ConfigBase
    {
        public int Round { get; private set; }
        public string RoundName { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> CourseMap { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Round = ByteConfigReader.GetInt32(binaryReader);
            RoundName = ByteConfigReader.GetString(binaryReader);
            CourseMap = ByteConfigReader.GetIntIntDic(binaryReader);
        }
    }
    
    public class HundredPlayoffCourseConfigTable : IdentityConfigTable<HundredPlayoffCourseConfig> { }
}

