
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class JerseyBreakConfig : ConfigBase
    {
        public int Position { get; private set; }
        public int Level { get; private set; }
        public string Cost { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> Ability { get; private set; }
        public int Quality { get; private set; }
        public int Talent { get; private set; }
        public string CardNameSuffix { get; private set; }
        public int CardLevel { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Position = ByteConfigReader.GetInt32(binaryReader);
            Level = ByteConfigReader.GetInt32(binaryReader);
            Cost = ByteConfigReader.GetString(binaryReader);
            Ability = ByteConfigReader.GetIntIntDic(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            Talent = ByteConfigReader.GetInt32(binaryReader);
            CardNameSuffix = ByteConfigReader.GetString(binaryReader);
            CardLevel = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class JerseyBreakConfigTable : IdentityConfigTable<JerseyBreakConfig> { }
}

