
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class LangConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string Desc { get; private set; }
        public string Content { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class LangConfigTable : IdentityConfigTable<LangConfig> { }
}

