
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class LeagueRewardOtherConfig : ConfigBase
    {
        public string DescText { get; private set; }
        public string Reward { get; private set; }
        public string MailTitle { get; private set; }
        public string MailContent { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            DescText = ByteConfigReader.GetString(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            MailTitle = ByteConfigReader.GetString(binaryReader);
            MailContent = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class LeagueRewardOtherConfigTable : IdentityConfigTable<LeagueRewardOtherConfig> { }
}

