
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ModuleDefineConfig : ConfigBase
    {
        public string Name { get; private set; }
        public string Icon { get; private set; }
        public int Forcego { get; private set; }
        public string Desc { get; private set; }
        public int Conversation { get; private set; }
        public string RewardsPreview { get; private set; }
        public string Pic { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Icon = ByteConfigReader.GetString(binaryReader);
            Forcego = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Conversation = ByteConfigReader.GetInt32(binaryReader);
            RewardsPreview = ByteConfigReader.GetString(binaryReader);
            Pic = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ModuleDefineConfigTable : IdentityConfigTable<ModuleDefineConfig> { }
}

