
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class MonthCardShopConfig : ConfigBase
    {
        public string ProductId { get; private set; }
        public string Obtain { get; private set; }
        public string EveryDay { get; private set; }
        public float Rmb { get; private set; }
        public float Dollar { get; private set; }

        private string __Name;
        public string Name 
        { 
            get => Babu.Globalization.Globalizer.Instance.GetGlobalizationText(__Name);
            private set => __Name = value; 
        }

        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            ProductId = ByteConfigReader.GetString(binaryReader);
            Obtain = ByteConfigReader.GetString(binaryReader);
            EveryDay = ByteConfigReader.GetString(binaryReader);
            Rmb = ByteConfigReader.GetFloat32(binaryReader);
            Dollar = ByteConfigReader.GetFloat32(binaryReader);
        }
    }
    
    public class MonthCardShopConfigTable : IdentityConfigTable<MonthCardShopConfig> { }
}

