
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class MoonSiginRewardConfig : ConfigBase
    {
        public string Content { get; private set; }
        public string Content30 { get; private set; }
        public string Content28 { get; private set; }
        public string Content29 { get; private set; }
        public int Type { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            Content30 = ByteConfigReader.GetString(binaryReader);
            Content28 = ByteConfigReader.GetString(binaryReader);
            Content29 = ByteConfigReader.GetString(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class MoonSiginRewardConfigTable : IdentityConfigTable<MoonSiginRewardConfig> { }
}

