
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class NftGoodsConfig : ConfigBase
    {
        public float Scale { get; private set; }
        public float ZOffset { get; private set; }
        public string Buffname { get; private set; }
        public int Price { get; private set; }
        public int Buffparam { get; private set; }
        public int Pic { get; private set; }

        private string __Name;
        public string Name 
        { 
            get => Babu.Globalization.Globalizer.Instance.GetGlobalizationText(__Name);
            private set => __Name = value; 
        }

        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Scale = ByteConfigReader.GetFloat32(binaryReader);
            ZOffset = ByteConfigReader.GetFloat32(binaryReader);
            Buffname = ByteConfigReader.GetString(binaryReader);
            Price = ByteConfigReader.GetInt32(binaryReader);
            Buffparam = ByteConfigReader.GetInt32(binaryReader);
            Pic = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class NftGoodsConfigTable : IdentityConfigTable<NftGoodsConfig> { }
}

