
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class NoviceTargetTaskConfig : ConfigBase
    {
        public int Day { get; private set; }
        public int Type { get; private set; }
        public int TriggerId { get; private set; }
        public int Target { get; private set; }
        public int Way { get; private set; }
        public string Reward { get; private set; }
        public int ModuleId { get; private set; }

        private string __Name;
        public string Name 
        { 
            get => Babu.Globalization.Globalizer.Instance.GetGlobalizationText(__Name);
            private set => __Name = value; 
        }

        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Day = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            TriggerId = ByteConfigReader.GetInt32(binaryReader);
            Target = ByteConfigReader.GetInt32(binaryReader);
            Way = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            ModuleId = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class NoviceTargetTaskConfigTable : IdentityConfigTable<NoviceTargetTaskConfig> { }
}

