
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class NpcCardConfig : ConfigBase
    {
        public int ClubId { get; private set; }
        public int ModelId { get; private set; }
        public int Star { get; private set; }
        public int[] Skills { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ClubId = ByteConfigReader.GetInt32(binaryReader);
            ModelId = ByteConfigReader.GetInt32(binaryReader);
            Star = ByteConfigReader.GetInt32(binaryReader);
            Skills = ByteConfigReader.GetInt32Array(binaryReader);
        }
    }
    
    public class NpcCardConfigTable : IdentityConfigTable<NpcCardConfig> { }
}

