
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class OptionsConfig : ConfigBase
    {
        public int Type { get; private set; }
        public string Content { get; private set; }
        public int Value { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Content = ByteConfigReader.GetString(binaryReader);
            Value = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class OptionsConfigTable : IdentityConfigTable<OptionsConfig> { }
}

