
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class SeparatedPositionConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Position { get; private set; }
        public string Abbreviation { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> AbilityRatio { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Position = ByteConfigReader.GetInt32(binaryReader);
            Abbreviation = ByteConfigReader.GetString(binaryReader);
            AbilityRatio = ByteConfigReader.GetIntIntDic(binaryReader);
        }
    }
    
    public class SeparatedPositionConfigTable : IdentityConfigTable<SeparatedPositionConfig> { }
}

