
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ShootGameStageConfig : ConfigBase
    {
        public int Point { get; private set; }
        public int FinishPoint { get; private set; }
        public int Second { get; private set; }
        public int[] ServeBall { get; private set; }
        public float SlideParam { get; private set; }
        public float ShakeParam { get; private set; }
        public string Reward { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Point = ByteConfigReader.GetInt32(binaryReader);
            FinishPoint = ByteConfigReader.GetInt32(binaryReader);
            Second = ByteConfigReader.GetInt32(binaryReader);
            ServeBall = ByteConfigReader.GetInt32Array(binaryReader);
            SlideParam = ByteConfigReader.GetFloat32(binaryReader);
            ShakeParam = ByteConfigReader.GetFloat32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ShootGameStageConfigTable : IdentityConfigTable<ShootGameStageConfig> { }
}

