
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class ShootGameAddedRewardConfig : ConfigBase
    {
        public int Point { get; private set; }
        public string Reward { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Point = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class ShootGameAddedRewardConfigTable : IdentityConfigTable<ShootGameAddedRewardConfig> { }
}

