
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class SkillUpgradeConfig : ConfigBase
    {
        public int Quality { get; private set; }
        public int TargetLevel { get; private set; }
        public int CostMoney { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> CostGoods { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            TargetLevel = ByteConfigReader.GetInt32(binaryReader);
            CostMoney = ByteConfigReader.GetInt32(binaryReader);
            CostGoods = ByteConfigReader.GetIntIntDic(binaryReader);
        }
    }
    
    public class SkillUpgradeConfigTable : IdentityConfigTable<SkillUpgradeConfig> { }
}

