
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class SkillConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Quality { get; private set; }
        public int Type { get; private set; }
        public int Icon { get; private set; }
        public string Desc { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> UnlockConditions { get; private set; }
        public int UnlockMoney { get; private set; }
        public int BuffType { get; private set; }
        public int[] BuffValue { get; private set; }
        public int[] EffectaddValue { get; private set; }
        public int TrainTime { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Quality = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Icon = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            UnlockConditions = ByteConfigReader.GetIntIntDic(binaryReader);
            UnlockMoney = ByteConfigReader.GetInt32(binaryReader);
            BuffType = ByteConfigReader.GetInt32(binaryReader);
            BuffValue = ByteConfigReader.GetInt32Array(binaryReader);
            EffectaddValue = ByteConfigReader.GetInt32Array(binaryReader);
            TrainTime = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class SkillConfigTable : IdentityConfigTable<SkillConfig> { }
}

