
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class StrengthenConfig : ConfigBase
    {
        public float CostNum { get; private set; }
        public int CostUnit { get; private set; }
        public int BuffType { get; private set; }
        public float BuffValue { get; private set; }
        public string BuffValueShow { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            CostNum = ByteConfigReader.GetFloat32(binaryReader);
            CostUnit = ByteConfigReader.GetInt32(binaryReader);
            BuffType = ByteConfigReader.GetInt32(binaryReader);
            BuffValue = ByteConfigReader.GetFloat32(binaryReader);
            BuffValueShow = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class StrengthenConfigTable : IdentityConfigTable<StrengthenConfig> { }
}

