
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TacticsConfig : ConfigBase
    {
        public int Type { get; private set; }
        public string Name { get; private set; }
        public string Desc { get; private set; }
        public string Restrain { get; private set; }
        public int[] MainPosition { get; private set; }
        public int[] Restrain1 { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Restrain = ByteConfigReader.GetString(binaryReader);
            MainPosition = ByteConfigReader.GetInt32Array(binaryReader);
            Restrain1 = ByteConfigReader.GetInt32Array(binaryReader);
        }
    }
    
    public class TacticsConfigTable : IdentityConfigTable<TacticsConfig> { }
}

