
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TacticsTypeConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int PrefabsType { get; private set; }
        public string Tips { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            PrefabsType = ByteConfigReader.GetInt32(binaryReader);
            Tips = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class TacticsTypeConfigTable : IdentityConfigTable<TacticsTypeConfig> { }
}

