
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TacticsUpgradeConfig : ConfigBase
    {
        public int TacticsId { get; private set; }
        public int Level { get; private set; }
        public int CostCard { get; private set; }
        public System.Collections.Generic.Dictionary<int, int> PositionAdd { get; private set; }
        public int Kezhi { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            TacticsId = ByteConfigReader.GetInt32(binaryReader);
            Level = ByteConfigReader.GetInt32(binaryReader);
            CostCard = ByteConfigReader.GetInt32(binaryReader);
            PositionAdd = ByteConfigReader.GetIntIntDic(binaryReader);
            Kezhi = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class TacticsUpgradeConfigTable : IdentityConfigTable<TacticsUpgradeConfig> { }
}

