
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TaskConfig : ConfigBase
    {
        public int Type { get; private set; }
        public string Desc { get; private set; }
        public int NextTask { get; private set; }
        public int TriggerId { get; private set; }
        public string CompareType { get; private set; }
        public int Condition { get; private set; }
        public int Point { get; private set; }
        public string Reward { get; private set; }
        public int Way { get; private set; }
        public int Moduleid { get; private set; }
        public int Zlpoint { get; private set; }
        public int IsHide { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            NextTask = ByteConfigReader.GetInt32(binaryReader);
            TriggerId = ByteConfigReader.GetInt32(binaryReader);
            CompareType = ByteConfigReader.GetString(binaryReader);
            Condition = ByteConfigReader.GetInt32(binaryReader);
            Point = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            Way = ByteConfigReader.GetInt32(binaryReader);
            Moduleid = ByteConfigReader.GetInt32(binaryReader);
            Zlpoint = ByteConfigReader.GetInt32(binaryReader);
            IsHide = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class TaskConfigTable : IdentityConfigTable<TaskConfig> { }
}

