
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TaskRewardBoxConfig : ConfigBase
    {
        public string Desc { get; private set; }
        public int NeedPoint { get; private set; }
        public string Reward { get; private set; }
        public int Type { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            NeedPoint = ByteConfigReader.GetInt32(binaryReader);
            Reward = ByteConfigReader.GetString(binaryReader);
            Type = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class TaskRewardBoxConfigTable : IdentityConfigTable<TaskRewardBoxConfig> { }
}

