
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TowerChapterConfig : ConfigBase
    {
        public string Name { get; private set; }
        public int Number { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Number = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class TowerChapterConfigTable : IdentityConfigTable<TowerChapterConfig> { }
}

