
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TrainShopConfig : ConfigBase
    {
        public int Obtain { get; private set; }
        public int Limit { get; private set; }
        public int Diamond { get; private set; }

        private string __Name;
        public string Name 
        { 
            get => Babu.Globalization.Globalizer.Instance.GetGlobalizationText(__Name);
            private set => __Name = value; 
        }

        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Obtain = ByteConfigReader.GetInt32(binaryReader);
            Limit = ByteConfigReader.GetInt32(binaryReader);
            Diamond = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class TrainShopConfigTable : IdentityConfigTable<TrainShopConfig> { }
}

