
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class TrainConfig : ConfigBase
    {
        public Babu.BigNumber.BigNumber BaseAdd { get; private set; }
        public int BaseTime { get; private set; }
        public Babu.BigNumber.BigNumber BaseCost { get; private set; }
        public float CostAdd { get; private set; }
        public Babu.BigNumber.BigNumber UnlockReward { get; private set; }
        public int Attribute { get; private set; }
        public string Name { get; private set; }
        public string Desc { get; private set; }
        public string Cameraid { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            BaseAdd = ByteConfigReader.GetBigNumber(binaryReader);
            BaseTime = ByteConfigReader.GetInt32(binaryReader);
            BaseCost = ByteConfigReader.GetBigNumber(binaryReader);
            CostAdd = ByteConfigReader.GetFloat32(binaryReader);
            UnlockReward = ByteConfigReader.GetBigNumber(binaryReader);
            Attribute = ByteConfigReader.GetInt32(binaryReader);
            Name = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            Cameraid = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class TrainConfigTable : IdentityConfigTable<TrainConfig> { }
}

