
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class UserLevelConfig : ConfigBase
    {
        public int Exp { get; private set; }
        public int ExpTotal { get; private set; }
        public string Rewards { get; private set; }
        public int BountyTaskCount { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            Exp = ByteConfigReader.GetInt32(binaryReader);
            ExpTotal = ByteConfigReader.GetInt32(binaryReader);
            Rewards = ByteConfigReader.GetString(binaryReader);
            BountyTaskCount = ByteConfigReader.GetInt32(binaryReader);
        }
    }
    
    public class UserLevelConfigTable : IdentityConfigTable<UserLevelConfig> { }
}

