
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class WayOfDescConfig : ConfigBase
    {
        public string ModuleName { get; private set; }
        public string SubModuleName { get; private set; }
        public string Desc { get; private set; }
        public string DropItem { get; private set; }
        public string ItemRange { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            ModuleName = ByteConfigReader.GetString(binaryReader);
            SubModuleName = ByteConfigReader.GetString(binaryReader);
            Desc = ByteConfigReader.GetString(binaryReader);
            DropItem = ByteConfigReader.GetString(binaryReader);
            ItemRange = ByteConfigReader.GetString(binaryReader);
        }
    }
    
    public class WayOfDescConfigTable : IdentityConfigTable<WayOfDescConfig> { }
}

