
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Babu.Config;
using System.IO;

namespace GameConfig.Config
{
    public class WayOfGainConfig : ConfigBase
    {
        public int GameItemType { get; private set; }
        public int GameItemId { get; private set; }
        public int[] Way { get; private set; }


        public override void LoadFromBinary(BinaryReader binaryReader)
        {
            Id = ByteConfigReader.GetInt32(binaryReader);
            GameItemType = ByteConfigReader.GetInt32(binaryReader);
            GameItemId = ByteConfigReader.GetInt32(binaryReader);
            Way = ByteConfigReader.GetInt32Array(binaryReader);
        }
    }
    
    public class WayOfGainConfigTable : IdentityConfigTable<WayOfGainConfig> { }
}

